### ISSUE TITLE
Fix code duplication in the newHash (Triage on ostracon#509)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#14]
The subject of the triage:
- Finschia/ostracon#509

**Comment by Mdaiki0730** [comment]
As of v0.38.0, there is no function with the same name, but there is a function that seems to be an alternative.
https://github.com/cometbft/cometbft/blob/v0.38.0/p2p/pex/addrbook.go#L112-L119

This seems to have been fixed by tendermint#9445 to improve performance.
The code written in `crypto.CRandBytes` has been modified to be reused.
https://github.com/tendermint/tendermint/pull/9445

It seems that there is no need to reflect it in cometbft.
