### ISSUE TITLE
improve performance of a crypt marshaller (ostracon#177)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#2]
The subject of the triage:
- Finschia/ostracon#177

**Comment by loloicci** [comment]
This is a PR for performance test and this PR says

> Please note that it's not production ready quality

If we need this improvement in the main branch, it may need other PRs to improve it.

**Comment by Mdaiki0730** [comment]
Performance seems to be improved, so we can create a PR after considering what we need for main branch.

**Comment by loloicci** [comment]
@Mdaiki0730 

> Performance seems to be improved, so we can create a PR after considering what we need for main branch.

I think it is worth merging into the main form the view point of performance.
But, do you know why it's not production-ready quality? Or, do you know some improvements for it?

**Comment by Mdaiki0730** [comment]
@loloicci 
The custom marshaler code is duplicated and needs to be packaged.

> we need more test code for production.

As for the further tests mentioned in the PR, I don't know what to do.

**Comment by Mdaiki0730** [comment]
By the way, the relevant parts of the crypto package have changed significantly in cometbft v0.38.0.
Looks like it was changed in tendermint#4950.
cometbft v0.38.0: https://github.com/cometbft/cometbft/blob/v0.38.0/crypto/ed25519/ed25519.go#L68-L70
PR: https://github.com/tendermint/tendermint/pull/4950

Ostracon#177 doesn't seem to be necessary since it returns a byte slice directly instead of an amino-marshalled byte slice.

**Comment by loloicci** [comment]
Thank you @Mdaiki0730 . I close this issue.
